server:
  port: 8009
  forward-headers-strategy: framework
  servlet:
    contextPath: /

spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/${spring.data.mongodb.database}?authSource=${spring.data.mongodb.authentication-database}&readPreference=primaryPreferred&directConnection=true
      host: localhost
      port: 27017
      database: gms-tenants
      username: root
      password: root
      auto-index-creation: true
      authentication-database: admin

openapi:
  service:
    title: GMS Multi Tenants
    version: 1.0
    description: IAM Service for GMS
    url: http://127.0.0.1:8009
    contact:
      name: GMS Team
      url: https://github.com/jesseballera/multi-tenant-mongodb